<?php
/**
 * AotolChat creates a floating chat box on your website.
 *
 * @package AotolChat - Free chat box for your website
 * @author Aotol Pty Ltd
 * @license GPL-2.0+
 * @link https://company.aotol.com/aotolchat/
 * @copyright 2020 Aotol Pty Ltd. All rights reserved.
 *
 *            @wordpress-plugin
 *            Plugin Name: AotolChat - Free chat box for your website
 *            Plugin URI: https://company.aotol.com/aotolchat/
 *            Description: AotolChat creates a floating chat box on your website so customers can talk to you in real time. You can find AotolChat plugin under Settings in left-side menu after activation.
 *            Version: 1.0
 *            Author: Aotol Pty Ltd
 *            Author URI: https://company.aotol.com
 *            Text Domain: aotolchat
 *            Contributors: Aotol Pty Ltd
 *            License: GPL-2.0+
 *            License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */
 
/**
 * Adding Submenu under Settings Tab
 *
 * @since 1.0
 */
function aotolchat_add_menu() {
	add_submenu_page ( "options-general.php", "AotolChat Plugin", "AotolChat Plugin", "manage_options", "aotolchat", "aotolchat_plugin_page" );
}
add_action ( "admin_menu", "aotolchat_add_menu" );
 
/**
 * Setting Page Options
 * - add setting page
 * - save setting page
 *
 * @since 1.0
 */
function aotolchat_plugin_page() {
	?>
<div class="wrap">
	<h1>
		AotolChat plugin by <a href="https://company.aotol.com" target="_blank">Aotol Pty Ltd</a>
	</h1>
 
	<form method="post" action="options.php">
            <?php
	settings_fields ( "aotolchat_config" );
	do_settings_sections ( "aotolchat" );
	submit_button ();
	?>
         </form>
</div>
 
<?php
}
 
/**
 * Init setting section, Init setting field and register settings page
 *
 * @since 1.0
 */
function aotolchat_settings() {
	add_settings_section ( "aotolchat_config", "", null, "aotolchat" );
	add_settings_field ( "aotolchat-code", "", "aotolchat_options", "aotolchat", "aotolchat_config" );
	register_setting ( "aotolchat_config", "aotolchat-code" );
}
add_action ( "admin_init", "aotolchat_settings" );
 
/**
 * Add simple textfield value to setting page
 *
 * @since 1.0
 */
function aotolchat_options() {
	?>
<div class="postbox" style="width: 70%; padding: 30px;">
	<div>
		Please enter the code generated by <a href="https://company.aotol.com/aotolchat" target="_blank">AotolChat mobile app</a>
	</div>
	<br>
	<div>
		<b>
			Instructions
		</b>
	</div>
	<div>
		<ul>
			<li>
				1. Download our AotolChat mobile app from <a href="https://play.google.com/store/apps/details?id=com.aotol.aotolchat" target="_blank">GooglePlay</a> or <a href="https://apps.apple.com/au/app/aotolchat/id1536058601" target="_blank">AppStore</a>.
			</li>
			<li>
				2. Launch the mobile app on your phone.
			</li>
			<li>
				3. After you signed in the app, scroll to "Advanced function" and expend it.
			</li>
			<li>
				4. Tap on the script code displayed under "Advanced function" to send the code to your email.
			</li>
			<li>
				5. Copy and paste the code in the email to the input box below and save it.
			</li>
		</ul>
	</div>
	<input type="text" size="40" name="aotolchat-code" placeholder="Enter the code here"
		value="<?php
	echo stripslashes_deep ( esc_attr ( get_option ( 'aotolchat-code' ) ) );
	?>" />
	<br><br>
	<div>
		That's it! A floating chat box will be displayed on your website and you will be notified on your mobile phone when someone send you message.
	</div>
</div>
<?php
}
 
/**
 * Append saved textfield value to each post
 *
 * @since 1.0
 */
add_filter ( 'the_content', 'aotolchat_com_content' );
function aotolchat_com_content($content) {
	return $content . stripslashes_deep (  get_option ( 'aotolchat-code' )  );
}